### ISSUE TITLE
Using This as a template

### ISSUE THREAD

**Issue by mraza007** [j7k6/docs.j7k6.org#1]
Hey !
Can I use this as template. 
I really love this

**Comment by j7k6** [comment]
Hi! Sorry for the late reply... Glad you like it ;) Feel free to use it as a template, but keep in mind that this is not intended to be used as generic scuffolding because at some point content and styles are not really separated from each other, you have to figure that out for yourself. Maybe make a link to my website (docs.j7k6.org) if you use this as a template (optional).

**Comment by mraza007** [comment]
A quick question how can I implement search

**Comment by j7k6** [comment]
It's not a real search, it just hides and shows elements which titles' match the search terms.

**Comment by mraza007** [comment]
Oh okay
Yeah I liked that most
I thought you were using full text search

**Comment by j7k6** [comment]
No, unfortunately full text search is not possible since its a static site. I guess it would be possible somehow with some pre-generated search index, but I never needed it, so it's just the way it is.

**Comment by mraza007** [comment]
Oh okay yeah that makes sense.
